### ISSUE TITLE
NFL History wrong Division

### ISSUE THREAD

**Issue by mamamia5x** [therri3n/FBGM-Therri3n#1]
![image](https://user-images.githubusercontent.com/57536929/167913289-d5616190-623b-4f09-b002-a5562e2ab347.png)
As you can see in the photo above, the NFC East has 6 teams, while the rest have 4. In reality, the Bears should be in the NFC Central. As seen in the photo above, this kinda screws up the playoffs, with the 4-6 Packers going in as the 3 seed, while the Bears 6-3 Bears should actually be in. I'm using [this](https://github.com/therri3n/FBGM-Therri3n/blob/main/NFL%20History/1920s/1921%20Update%201_4_22.json) file.

**Comment by therri3n** [comment]
This has already been resolved in an updated [file](https://github.com/therri3n/FBGM-Therri3n/blob/main/NFL%20History/FBGM_League_65_1921_preseason%20(1)%20(6).json). Individual years just have not been changed as I do not have the time to update and upload each individual year. Thank you.
